services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HTTP_ENABLED: true
    command: start-dev
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: ./api_gateway/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:80"
    depends_on:
      - service-classe
      - service-eleve
      - service-notification
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/ecole-realm
      - Keycloak__Audience=account

  service-classe:
    build:
      context: ./service_classe/service_classe
      dockerfile: Dockerfile
    container_name: service-classe
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/ecole-realm

  service-eleve:
    build:
      context: ./service_eleve/service_eleve
      dockerfile: Dockerfile
    container_name: service-eleve
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/ecole-realm

  service-notification:
    build:
      context: ./service_notification/service_notification
      dockerfile: Dockerfile
    container_name: service-notification
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/ecole-realm